version: '3.7'

services:
  rest-api:
    image: '${APP_NAME}:latest'
    build:
      context: ./
      target: production-build-stage
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/${APP_NAME}
    restart: 'unless-stopped'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${APP_PORT}/health-check']
      interval: 30s
      timeout: 5s
      retries: 3